<!doctype html>
<html class="no-js" lang="en">
    <head>
        <?php include_once 'predlozak/head.phtml' ?>
    </head>
<body>
    <div class="grid-container">
        <?php include_once 'predlozak/izbornik.phtml' ?>
        <div id='program' class="callout">
            <?=$sadrzaj?>
        </div>
        <?php include_once 'predlozak/podnozje.phtml' ?>
    </div>

<?php include_once 'predlozak/skripte.phtml' ?>
</body>
</html>