<div class="title-bar" data-responsive-toggle="responsive-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle="responsive-menu"></button>
  <div class="title-bar-title">Menu</div>
</div>

<div class="top-bar" id="responsive-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li>
        <a href="<?=App::config('url')?>">
            <?=App::config('nazivApp')?>
        </a>
      </li>
      <?php if(isset($_SESSION['autoriziran'])): ?>
      <a href="<?=App::config('url')?>nadzornaploca/index">Nadzorna Ploca</a>
      <?php endif;?>
      <li><a href="<?=App::config('url')?>index/era">ERA</a></li>
      <li><a href="<?=App::config('url')?>index/kontakt">Kontakt</a></li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li>
      <?php if(!isset($_SESSION['autoriziran'])): ?>
        <a href="<?=App::config('url')?>index/login">Autoriziraj</a>
      <?php else: ?>
        <a href="<?=App::config('url')?>index/logout">Odjava</a>
      <?php endif;?>
      </li>
    </ul>
  </div>
</div>