<div class="title-bar" data-responsive-toggle="responsive-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle="responsive-menu"></button>
  <div class="title-bar-title">Menu</div>
</div>

<div class="top-bar" id="responsive-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li>
        <a href="<?=App::config('url')?>">
            <?=App::config('nazivApp')?>
        </a>
      </li>
      <li><a href="<?=App::config('url')?>index/era">ERA</a></li>
      <li><a href="<?=App::config('url')?>index/kontakt">Kontakt</a></li>
      <li <?php 
      if(in_array($_SERVER['REQUEST_URI'],[
        '/papir/index',
        '/racun/index',
        '/djelatnik/index',
        '/usluga/index'
        ])){
        echo 'class="active"';
      }?>>
      <a href="#">Ponuda</a>
          <ul class="vertical menu">
            <li <?php 
              if($_SERVER['REQUEST_URI']=='/papir/index'){
                echo 'class="active"';
              }?>>
            <a href="<?=App::config('url')?>papir/index">Papir</a></li>
            <li <?php 
              if($_SERVER['REQUEST_URI']=='/racun/index'){
                echo 'class="active"';
              }?>><a href="<?=App::config('url')?>racun/index">Račun</a></li>
            <li <?php 
              if($_SERVER['REQUEST_URI']=='/djelatnik/index'){
                echo 'class="active"';
              }?>><a href="<?=App::config('url')?>djelatnik/index">Djelatnik</a></li>
            <li <?php 
              if($_SERVER['REQUEST_URI']=='/usluga/index'){
                echo 'class="active"';
              }?>><a href="<?=App::config('url')?>usluga/index">Usluga</a></li>
          </ul>
        </li>
      <?php if(isset($_SESSION['autoriziran'])): ?>
        <li><a href="<?=App::config('url')?>nadzornaploca/index"><?=$_SESSION['autoriziran']->ime?> <?=$_SESSION['autoriziran']->prezime?> | <?=$_SESSION['autoriziran']->uloga?></a></li>
      <?php endif;?>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li>
      <?php if(!isset($_SESSION['autoriziran'])): ?>
        <a href="<?=App::config('url')?>index/login">Autoriziraj</a>
      <?php else: ?>
        <a href="<?=App::config('url')?>index/logout">Odjava</a>
      <?php endif;?>
      </li>
    </ul>
  </div>
</div>