<form class="log-in-form" 
    action="<?=App::config('url')?>racun/promjena"
    method="POST">
  <h4 class="text-center">Dodavanje novog racuna</h4>
  <label>Klijent
    <input type="text" name="klijent" value="<?=$racun->klijent?>">
  </label>
  <label>Djelatnik
    <select name="djelatnik">
        <?php foreach($djelatnici as $djelatnik): ?>
            <option <?= $racun->djelatnik === $djelatnik->sifra ? 'selected' : '' ?> value="<?= $djelatnik->sifra ?>"><?= $djelatnik->ime . ' ' . $djelatnik->prezime ?></option>
        <?php endforeach ?>
    </select>
  </label>
  <label>Usluga
    <select name="usluga">
        <?php foreach($vrsteUsluga as $vrstaUsluge): ?>
            <option <?= $racun->usluga === $vrstaUsluge->sifra ? 'selected' : '' ?> value="<?= $vrstaUsluge->sifra ?>"><?= $vrstaUsluge->naziv ?></option>
        <?php endforeach ?>
    </select>
  </label>
  <label>Papir
    <select name="papir">
        <?php foreach($vrstePapira as $vrstaPapira): ?>
            <option <?= $racun->papir === $vrstaPapira->sifra ? 'selected' : '' ?> value="<?= $vrstaPapira->sifra ?>"><?= $vrstaPapira->vrstapapira ?></option>
        <?php endforeach ?>
    </select>
  </label>
  
  <?=$poruka?>
<div class="grid-x grid-padding-x">
  <div class="cell small-6 medium-6 large-6">
    <a class="alert button expanded"
    href="<?=App::config('url')?>usluga/index">Nazad</a>
  </div>
  <div class="cell small-6 medium-6 large-6">
    <input type="submit" class="button expanded" value="Dodaj"></input></p>
  </div>
</div>
<input type="hidden" name="sifra" value="<?=$racun->sifra?>">
</form>