<h1 style="font-size: 1em;">Usluga</h1>
<a href="<?=App::config('url')?>usluga/novo">Dodaj novu uslugu</a>
<ul>
<?php foreach($usluge as $usluga): ?>
    <li>
        <?=$usluga->naziv?>
        <a href="<?=App::config('url')?>usluga/promjena?sifra=<?=$usluga->sifra?>">
            Promjeni
        </a>
        <?php if($usluga->ukupnopapira==0):?>
            <a href="<?=App::config('url')?>usluga/brisanje?sifra=<?=$usluga->sifra?>"
            onclick="return confirm('Sigurno obrisati <?=$usluga->naziv?>?');"
            >Obriši</a>
        <?php endif;?>
    </li>
<?php endforeach; ?>
</ul>