<form class="log-in-form" 
    action="<?=App::config('url')?>usluga/promjena"
    method="POST">
  <h4 class="text-center">Promjena usluge</h4>
  <label>Naziv
    <input type="text" name="naziv" value="<?=$usluga->naziv?>">
  </label>
  <label>Cijena
    <input type="text" name="cijena" value="<?=$usluga->cijena?>">
  </label>
  <?=$poruka?>
<div class="grid-x grid-padding-x">
  <div class="cell small-6 medium-6 large-6">
    <a class="alert button expanded"
    href="<?=App::config('url')?>usluga/index">Nazad</a>
  </div>
  <div class="cell small-6 medium-6 large-6">
    <input type="submit" class="button expanded" value="Promjena"></input></p>
  </div>
</div>

</form>