<h1 style="font-size: 1em;">Papir</h1>
<a href="<?=App::config('url')?>papir/novo">Dodaj novi papir</a>
<ul>
<?php foreach($papiri as $papir): ?>
    <li>
        <?=$papir->vrstapapira?>
        <a href="<?=App::config('url')?>papir/promjena?sifra=<?=$papir->sifra?>">
            Promjeni
        </a>
        <?php if($papir->ukupnoRacuna==0):?>
            <a href="<?=App::config('url')?>papir/brisanje?sifra=<?=$papir->sifra?>"
            onclick="return confirm('Sigurno obrisati <?=$papir->naziv?>?');"
            >Obriši</a>
        <?php endif;?>
    </li>
<?php endforeach; ?>
</ul>