<form class="log-in-form" 
    action="<?=App::config('url')?>grupa/novo"
    method="POST">
  <h4 class="text-center">Dodavanje nove grupe</h4>



  <div class="grid-x grid-padding-x">
    <div class="cell large-6">
        <label>Naziv
          <input type="text" name="naziv" value="<?=$entitet->naziv?>">
        </label>
      </div>
    <div class="cell large-6">
      <label>Smjer
        <select name="smjer">
          <?php foreach($smjerovi as $smjer): ?>
            <option <?php 
              if($entitet->smjer==$smjer->sifra){
                echo ' selected="selected" ';
              }
              ?> value="<?=$smjer->sifra ?>"><?=$smjer->naziv ?></option>
          <?php endforeach; ?>
        </select>
      </label>
    </div>
  </div>



  <div class="grid-x grid-padding-x">
    <div class="cell large-6">
      <label>Datum početka
      <input type="datetime-local"
       name="datumpocetka" value="<?=$entitet->datumpocetka; ?>"> 
      </label>
    </div>
    <div class="cell large-6">
      <label>Predavač
      <select name="predavac">
          <?php foreach($predavaci as $predavac): ?>
            <option <?php 
              if($entitet->predavac==$predavac->sifra){
                echo ' selected="selected" ';
              }
              ?> value="<?=$predavac->sifra ?>"><?=$predavac->ime . ' ' . $predavac->prezime; ?></option>
          <?php endforeach; ?>
        </select>
      </label>
    </div>
  </div>
  
 
<div class="grid-x grid-padding-x">
    <div class="cell">
     <div class="callout">
      <?=$poruka?>
     </div>
    </div>
  </div>
  

<div class="grid-x grid-padding-x">
  <div class="cell small-6 medium-6 large-6">
    <a class="alert button expanded" 
        href="<?=App::config('url')?>grupa/index">Nazad</a>
  </div>
  <div class="cell small-6 medium-6 large-6">
    <input type="submit" class="button expanded" value="Dodaj"></input>
  </div>
</div>

</form>