<form class="log-in-form" 
    action="<?=App::config('url')?>papir/novo"
    method="POST">
  <h4 class="text-center">Dodavanje nove vrste papira</h4>
  <label>Vrsta
    <input type="text" name="vrstapapira" value="<?=$papir->vrstapapira?>">
  </label>
  <?=$poruka?>
<div class="grid-x grid-padding-x">
  <div class="cell small-6 medium-6 large-6">
    <a class="alert button expanded"
    href="<?=App::config('url')?>papir/index">Nazad</a>
  </div>
  <div class="cell small-6 medium-6 large-6">
    <input type="submit" class="button expanded" value="Dodaj"></input></p>
  </div>
</div>

</form>