<form class="log-in-form" 
    action="<?=App::config('url')?>grupa/promjena"
    method="POST">
  <h4 class="text-center">Promjena grupe</h4>



  <div class="grid-x grid-padding-x">
    <div class="cell large-6">
        <label>Naziv
          <input type="text" name="naziv" value="<?=$entitet->naziv?>">
        </label>
      </div>
    <div class="cell large-6">
      <label>Smjer
        <select name="smjer">
          <?php foreach($smjerovi as $smjer): ?>
            <option <?php 
              if($entitet->smjer==$smjer->sifra){
                echo ' selected="selected" ';
              }
              ?> value="<?=$smjer->sifra ?>"><?=$smjer->naziv ?></option>
          <?php endforeach; ?>
        </select>
      </label>
    </div>
  </div>



  <div class="grid-x grid-padding-x">
    <div class="cell large-6">
      <label>Datum početka
      <input type="datetime-local"
       name="datumpocetka" value="<?=$entitet->datumpocetka; ?>"> 
      </label>
    </div>
    <div class="cell large-6">
      <label>Predavač
      <select name="predavac">
          <?php foreach($predavaci as $predavac): ?>
            <option <?php 
              if($entitet->predavac==$predavac->sifra){
                echo ' selected="selected" ';
              }
              ?> value="<?=$predavac->sifra ?>"><?=$predavac->ime . ' ' . $predavac->prezime; ?></option>
          <?php endforeach; ?>
        </select>
      </label>
    </div>
  </div>

  <div class="grid-x grid-padding-x">
    <div class="cell">
      <hr />
      <input type="text" id="uvjet"
            placeholder="Unesite dio imena ili prezimena ili OIB-a">
      <table>
        <thead>
          <tr>
            <th>Polaznik</th>
            <th>Akcija</th>
          </tr>
        </thead>
        <tbody id="polaznici">
        <?php foreach($entitet->polaznici as $red): ?>
            <tr>
                <td><?=$red->ime . ' ' . $red->prezime;?></td>
                <td>
                <a class="brisanje" href="#" 
                id="p_<?=$red->sifra?>">
                        <i title="brisanje" style="color: red" 
                        class="fas fa-trash-alt"></i>
                        </a>
                </td>
            </tr>

        <?php endforeach; ?>
        </tbody>
      </table>
      <hr />
    </div>
  </div>
  
 
<div class="grid-x grid-padding-x">
    <div class="cell">
     <div class="callout">
      <?=$poruka?>
     </div>
    </div>
  </div>
  

<div class="grid-x grid-padding-x">
  <div class="cell small-6 medium-6 large-6">
    <a class="alert button expanded" 
        href="<?=App::config('url')?>grupa/index">Nazad</a>
  </div>
  <div class="cell small-6 medium-6 large-6">
    <input type="submit" class="button expanded" value="Promjeni"></input>
  </div>
</div>
<input type="hidden" name="sifra" value="<?=$entitet->sifra?>">
</form>
<script>
let grupa=<?=$entitet->sifra?>;
</script>