<form class="log-in-form" 
    action="<?=App::config('url')?>djelatnik/novo"
    method="POST">
  <h4 class="text-center">Dodavanje novog djelatnika</h4>
  <div class="grid-x grid-padding-x">
    <div class="cell large-6">
        <label>Ime
          <input type="text" name="ime" value="<?=$entitet->ime?>">
        </label>
      </div>
    <div class="cell large-6">
      <label>Prezime
        <input type="text"  name="prezime" value="<?=$entitet->prezime?>">
      </label>
    </div>
  </div>

  <div class="grid-x grid-padding-x">
    <div class="cell">
      <label>Email
        <input type="email" name="email" value="<?=$entitet->email?>">
      </label>
    </div>
  </div>


  <div class="grid-x grid-padding-x">
    <div class="cell large-6">
      <label>OIB
        <input type="text" name="oib" value="<?=$entitet->oib?>">
      </label>
    </div>
    <div class="cell large-6">
      <label>IBAN
        <input type="text"  name="iban" value="<?=$entitet->iban?>">
      </label>
    </div>
  </div>
  
 
<div class="grid-x grid-padding-x">
    <div class="cell">
     <div class="callout">
      <?=$poruka?>
     </div>
    </div>
  </div>
  

<div class="grid-x grid-padding-x">
  <div class="cell small-6 medium-6 large-6">
    <a class="alert button expanded" 
        href="<?=App::config('url')?>djelatnik/index">Nazad</a>
  </div>
  <div class="cell small-6 medium-6 large-6">
    <input type="submit" class="button expanded" value="Dodaj"></input>
  </div>
</div>

</form>